language: php
php:
  - '7.4'
branches:
  only:
    - main
cache:
  directories:
    - $HOME/.composer/cache
notifications:
  email:
    - brucesnack@outlook.com
script:
  # flags to pass to install
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  # install dependencies using system provided composer binary
  - composer install $flags
  - cp config/.env.example config/.env
  - composer archive -f zip --file release
before_deploy:
  - git config --local user.name "livissnack"
  - git config --local user.email "brucesnack@outlook.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-v1.$(date +'%y%m%d').$(date +'%H%M%S')}
  - git tag $TRAVIS_TAG --force
  - env
  - export RELEASE_NAME=${TRAVIS_REPO_SLUG/\//_}_$TRAVIS_TAG.zip
  - mv release.zip $RELEASE_NAME
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  name: $TRAVIS_TAG
  overwrite: true
  api_key: $GITHUB_TOKEN
  file:
    - $RELEASE_NAME
  skip_cleanup: true
  on:
    branch: main
